### PR TITLE
Chaz search improve

### PR DESCRIPTION
**Pull request by chazhenricks**
## REFERENCE

N/A

## DESCRIPTION
Made the search function better. 
Filtered results by converting the search term to lowercase and comparing it with the product name that has also been converted to lower case. 
Search also returns results if a product name contains the search term at all 

## STEPS TO TEST
1.Search for `C`
1. you should see a list of results that contain the letter C
1. searching for `cool` should return result 'COOL' (if that item is in your database)

### CODE REVIEW

**Comment by augsismyburger** [comment]
Works 👍

**Comment by madelineepower** [comment]
coolio

**Comment by chazhenricks** [comment]
Location search should be working properly. 
Will need to burn down DB and build again.

**Comment by augsismyburger** [comment]
Now ever more better. 👍

**Comment by madelineepower** [comment]
👍 location search

**Pull request merged**
